/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Speed (https://sketchfab.com/Speeedd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-gamer-d8377cf2be84432f96f1e547e060ad35
Title: Laptop gamer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ASSET_ASSET_MAT_MR_0.geometry} material={materials.ASSET_MAT_MR} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
